set(OpenCV_INCLUDE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/extra/opencv/build/install/include)
set(OpenCV_LIBRARY_DIR ${CMAKE_CURRENT_SOURCE_DIR}/extra/opencv/build/install/lib)
set(LIBPREFIX "${CMAKE_SHARED_LIBRARY_PREFIX")
set(LIBSUFFIX "${CMAKE_SHARED_LIBRARY_SUFFIX")
set(OpenCV_LIBRARY "${OpenCV_LIBRARY_DIR}/${LIBPREFIX}OpenCV{LIBSUFFIX}")


add_library(OpenCV IMPORTED SHARED GLOBAL)

set_target_properties(OpenCV PROPERTIES
        IMPORTED_LOCATION                   "${OpenCV_LIBRARY}"
        INTERFACE_INCLUDE_DIRECTORIES       "${OpenCV_INCLUDE_DIR}"
        IMPORTED_LINK_INTERFACE_LIBRARIES   "${CMAKE_THREAD_LIBS_INIT}"
)


message( "-- found OpenCV: TRUE" )

message( "LIBPREFIX= "${LIBPREFIX} )
message( "LIBSUFFIX= ")${LIBSUFFIX} )